-- =============================================================================
-- 3DMCC — Seed: Courses & Jobs
-- =============================================================================

insert into public.courses (
  id, slug, title_en, title_ar,
  short_description_en, short_description_ar,
  full_description_en, full_description_ar,
  learning_objectives_en, learning_objectives_ar,
  curriculum_en, curriculum_ar,
  target_audience_en, target_audience_ar,
  prerequisites_en, prerequisites_ar,
  category_id, duration, delivery_type, instructor_en, instructor_ar,
  price, currency, availability, status, featured, sort_order
) values
(
  'f1000000-0000-0000-0000-000000000001',
  'practical-hrm-courses',
  'Practical HRM Courses', 'دورات عملية في إدارة الموارد البشرية',
  'Hands-on HR management training covering the full employee lifecycle.',
  'تدريب عملي في إدارة الموارد البشرية يغطي دورة حياة الموظف الكاملة.',
  'A practical HRM program designed for professionals who want to apply modern HR practices in real organizations, covering recruitment, performance, compensation, employee relations and HR systems.',
  'برنامج عملي في إدارة الموارد البشرية مصمم للمهنيين الراغبين في تطبيق ممارسات HR الحديثة في مؤسسات حقيقية، ويغطي التوظيف والأداء والتعويضات وعلاقات الموظفين وأنظمة HR.',
  '["Apply the full HR lifecycle","Design performance and compensation systems","Use HR tools and systems confidently","Align HR with business strategy"]',
  '["تطبيق دورة حياة الموارد البشرية الكاملة","تصميم أنظمة الأداء والتعويضات","استخدام أدوات وأنظمة HR بثقة","مواءمة الموارد البشرية مع استراتيجية العمل"]',
  '["Introduction to modern HR","Recruitment and selection","Performance management","Compensation and benefits","Employee relations","HR systems and analytics"]',
  '["مقدمة في الموارد البشرية الحديثة","التوظيف والاختيار","إدارة الأداء","التعويضات والمزايا","علاقات الموظفين","أنظمة وتحليلات HR"]',
  '["HR practitioners","Managers and team leads","Professionals transitioning into HR"]',
  '["ممارسو الموارد البشرية","المديرون وقادة الفرق","المهنيون المنتقلون إلى HR"]',
  '["Basic understanding of business operations","No advanced HR experience required"]',
  '["فهم أساسي لعمليات الأعمال","لا يلزم خبرة متقدمة في HR"]',
  'c0000000-0000-0000-0000-000000000001', '24 hours', 'In-person / Online', '3DMCC Training Team', 'فريق تدريب 3DMCC',
  350, 'JOD', 'Open for registration', 'published', true, 1
),
(
  'f1000000-0000-0000-0000-000000000002',
  'scientific-research-skills',
  'Scientific Research Skills', 'مهارات البحث العلمي',
  'Build rigorous research skills from design to analysis and publication.',
  'اكتسب مهارات بحثية دقيقة من التصميم إلى التحليل والنشر.',
  'This course equips participants with the skills to design, conduct and present scientific research, covering research questions, methodology, data collection and analysis, and academic writing.',
  'تزوّد هذه الدورة المشاركين بالمهارات اللازمة لتصميم البحث العلمي وإجرائه وعرضه، وتغطي أسئلة البحث والمنهجية وجمع البيانات وتحليلها والكتابة الأكاديمية.',
  '["Formulate strong research questions","Choose appropriate methodology","Collect and analyze data","Write and present research effectively"]',
  '["صياغة أسئلة بحث قوية","اختيار المنهجية المناسبة","جمع البيانات وتحليلها","كتابة البحث وعرضه بفعالية"]',
  '["Research foundations","Research design and methodology","Data collection techniques","Data analysis","Academic writing and publication"]',
  '["أسس البحث","تصميم البحث والمنهجية","تقنيات جمع البيانات","تحليل البيانات","الكتابة الأكاديمية والنشر"]',
  '["Students and researchers","Professionals conducting studies","Academics improving research skills"]',
  '["الطلاب والباحثون","المهنيون الذين يجرون دراسات","الأكاديميون الراغبون في تطوير مهارات البحث"]',
  '["Basic computer literacy","Interest in research"]',
  '["إلمام أساسي بالحاسوب","اهتمام بالبحث"]',
  'c0000000-0000-0000-0000-000000000002', '20 hours', 'Online', '3DMCC Training Team', 'فريق تدريب 3DMCC',
  280, 'JOD', 'Open for registration', 'published', true, 2
),
(
  'f1000000-0000-0000-0000-000000000003',
  'ai-programming-languages',
  'AI & Programming Languages', 'الذكاء الاصطناعي ولغات البرمجة',
  'Learn modern programming and the fundamentals of applied AI.',
  'تعلّم البرمجة الحديثة وأساسيات الذكاء الاصطناعي التطبيقي.',
  'A practical course introducing programming fundamentals and modern languages, then progressing to core AI concepts and tools so participants can build simple intelligent applications.',
  'دورة عملية تقدم أساسيات البرمجة واللغات الحديثة، ثم تنتقل إلى مفاهيم وأدوات الذكاء الاصطناعي الأساسية ليتمكن المشاركون من بناء تطبيقات ذكية بسيطة.',
  '["Write programs in a modern language","Understand core programming concepts","Apply fundamental AI concepts","Build simple intelligent applications"]',
  '["كتابة برامج بلغة حديثة","فهم مفاهيم البرمجة الأساسية","تطبيق مفاهيم الذكاء الاصطناعي الأساسية","بناء تطبيقات ذكية بسيطة"]',
  '["Programming fundamentals","Python essentials","Data structures and algorithms","Introduction to AI","Machine learning basics","Building a project"]',
  '["أساسيات البرمجة","أساسيات بايثون","هياكل البيانات والخوارزميات","مقدمة في الذكاء الاصطناعي","أساسيات تعلم الآلة","بناء مشروع"]',
  '["Beginners in programming","Professionals upskilling in AI","Anyone curious about AI"]',
  '["المبتدئون في البرمجة","المهنيون الراغبون في تطوير مهارات الذكاء الاصطناعي","كل من لديه فضول حول الذكاء الاصطناعي"]',
  '["No prior programming experience required","Basic computer skills"]',
  '["لا يلزم خبرة برمجية سابقة","مهارات حاسوب أساسية"]',
  'c0000000-0000-0000-0000-000000000003', '30 hours', 'In-person / Online', '3DMCC Training Team', 'فريق تدريب 3DMCC',
  400, 'JOD', 'Open for registration', 'published', true, 3
),
(
  'f1000000-0000-0000-0000-000000000004',
  'business-intelligence-data-analytics',
  'Business Intelligence & Data Analytics', 'ذكاء الأعمال وتحليل البيانات',
  'Turn data into insights with BI tools and practical analytics techniques.',
  'حوّل البيانات إلى رؤى باستخدام أدوات ذكاء الأعمال وتقنيات التحليل العملي.',
  'This course teaches participants how to analyze data and build dashboards using modern BI tools, covering data preparation, visualization, and data-driven decision making.',
  'تعلّم هذه الدورة المشاركين كيفية تحليل البيانات وبناء لوحات المعلومات باستخدام أدوات ذكاء الأعمال الحديثة، وتغطي إعداد البيانات والتصور واتخاذ القرار المبني على البيانات.',
  '["Prepare and clean data","Build effective dashboards","Analyze and visualize data","Support data-driven decisions"]',
  '["إعداد البيانات وتنظيفها","بناء لوحات معلومات فعالة","تحليل البيانات وتصورها","دعم القرارات المبنية على البيانات"]',
  '["Introduction to data analytics","Data preparation","Data visualization","Dashboard design","Business intelligence tools","Analytics project"]',
  '["مقدمة في تحليل البيانات","إعداد البيانات","تصور البيانات","تصميم لوحات المعلومات","أدوات ذكاء الأعمال","مشروع تحليلي"]',
  '["Analysts and professionals","Managers making data decisions","Anyone working with business data"]',
  '["المحللون والمهنيون","المديرون الذين يتخذون قرارات بالبيانات","كل من يتعامل مع بيانات الأعمال"]',
  '["Basic Excel skills","Familiarity with business data"]',
  '["مهارات Excel أساسية","إلمام ببيانات الأعمال"]',
  'c0000000-0000-0000-0000-000000000004', '25 hours', 'Online', '3DMCC Training Team', 'فريق تدريب 3DMCC',
  380, 'JOD', 'Open for registration', 'published', true, 4
),
(
  'f1000000-0000-0000-0000-000000000005',
  'soft-skills-leadership',
  'Soft Skills & Leadership', 'المهارات الناعمة والقيادة',
  'Develop the communication, leadership and interpersonal skills that drive careers.',
  'طوّر مهارات التواصل والقيادة والتعامل مع الآخرين التي تدفع المسار المهني.',
  'A practical program focused on the soft skills that matter most in the workplace, including communication, emotional intelligence, teamwork and leadership, to help professionals grow and lead effectively.',
  'برنامج عملي يركز على المهارات الناعمة الأكثر أهمية في بيئة العمل، بما في ذلك التواصل والذكاء العاطفي والعمل الجماعي والقيادة، لمساعدة المهنيين على النمو والقيادة بفعالية.',
  '["Communicate with clarity and impact","Lead and motivate teams","Develop emotional intelligence","Collaborate effectively"]',
  '["التواصل بوضوح وتأثير","قيادة الفرق وتحفيزها","تطوير الذكاء العاطفي","التعاون بفعالية"]',
  '["Effective communication","Emotional intelligence","Teamwork and collaboration","Leadership fundamentals","Conflict resolution","Personal effectiveness"]',
  '["التواصل الفعال","الذكاء العاطفي","العمل الجماعي والتعاون","أساسيات القيادة","حل النزاعات","الفعالية الشخصية"]',
  '["Professionals at all levels","Team leads and managers","Anyone developing leadership skills"]',
  '["المهنيون على جميع المستويات","قادة الفرق والمديرون","كل من يطوّر مهارات القيادة"]',
  '["No prerequisites","Willingness to engage in practical activities"]',
  '["لا توجد متطلبات مسبقة","الاستعداد للمشاركة في الأنشطة العملية"]',
  'c0000000-0000-0000-0000-000000000005', '18 hours', 'In-person', '3DMCC Training Team', 'فريق تدريب 3DMCC',
  250, 'JOD', 'Open for registration', 'published', true, 5
);

-- ---------------------------------------------------------------------------
-- Jobs (demo vacancies — clearly marked sample until replaced)
-- ---------------------------------------------------------------------------
insert into public.jobs (
  id, slug, title_en, title_ar,
  department_en, department_ar,
  description_en, description_ar,
  responsibilities_en, responsibilities_ar,
  requirements_en, requirements_ar,
  qualifications_en, qualifications_ar,
  skills_en, skills_ar,
  location_en, location_ar, employment_type, status, sort_order
) values
(
  'f2000000-0000-0000-0000-000000000001',
  'hr-consultant',
  'HR Consultant (Sample)', 'مستشار موارد بشرية (نموذج)',
  'Human Resources', 'الموارد البشرية',
  'Support client organizations with HR advisory and implementation services. This is a sample vacancy used to demonstrate the careers system.',
  'دعم مؤسسات العملاء بخدمات الاستشارات والتنفيذ في الموارد البشرية. هذه وظيفة نموذجية لعرض نظام الوظائف.',
  '["Advise clients on HR policies and practices","Support HR outsourcing and payroll projects","Design performance management frameworks","Prepare HR documentation and reports"]',
  '["تقديم المشورة للعملاء حول سياسات وممارسات HR","دعم مشاريع تعهيد HR والرواتب","تصميم أطر إدارة الأداء","إعداد وثائق وتقارير HR"]',
  '["Bachelor''s degree in HR, business or related field","2+ years of HR experience","Strong knowledge of HR practices","Excellent Arabic and English"]',
  '["درجة البكالوريوس في الموارد البشرية أو إدارة الأعمال أو مجال ذي صلة","خبرة سنتين أو أكثر في HR","معرفة قوية بممارسات HR","إجادة العربية والإنجليزية"]',
  '["Professional HR certification is a plus","Consulting experience preferred"]',
  '["شهادة مهنية في HR ميزة إضافية","يفضَّل خبرة استشارية"]',
  '["Communication","Problem solving","HR systems","Client management"]',
  '["التواصل","حل المشكلات","أنظمة HR","إدارة العملاء"]',
  'Amman, Jordan', 'عمّان، الأردن', 'full_time', 'published', 1
),
(
  'f2000000-0000-0000-0000-000000000002',
  'business-development-specialist',
  'Business Development Specialist (Sample)', 'أخصائي تطوير أعمال (نموذج)',
  'Business Development', 'تطوير الأعمال',
  'Identify and develop new business opportunities and client relationships. Sample vacancy.',
  'تحديد وتطوير فرص عمل وعلاقات عملاء جديدة. وظيفة نموذجية.',
  '["Identify new client opportunities","Build and maintain client relationships","Prepare proposals and presentations","Support marketing and outreach"]',
  '["تحديد فرص عملاء جديدة","بناء علاقات العملاء والحفاظ عليها","إعداد العروض والتقديمات","دعم التسويق والتواصل"]',
  '["Bachelor''s degree in business or related field","2+ years in business development","Strong networking skills","Excellent communication"]',
  '["درجة البكالوريوس في إدارة الأعمال أو مجال ذي صلة","خبرة سنتين أو أكثر في تطوير الأعمال","مهارات تواصل قوية","تواصل ممتاز"]',
  '["Experience in consulting or services is a plus"]',
  '["خبرة في الاستشارات أو الخدمات ميزة إضافية"]',
  '["Sales","Negotiation","Market research","Relationship building"]',
  '["المبيعات","التفاوض","البحث السوقي","بناء العلاقات"]',
  'Amman, Jordan', 'عمّان، الأردن', 'full_time', 'published', 2
),
(
  'f2000000-0000-0000-0000-000000000003',
  'training-coordinator',
  'Training Coordinator (Sample)', 'منسق تدريب (نموذج)',
  'Training & Development', 'التدريب والتطوير',
  'Coordinate training programs and support course delivery and registration. Sample vacancy.',
  'تنسيق برامج التدريب ودعم تقديم الدورات والتسجيل. وظيفة نموذجية.',
  '["Coordinate training schedules and logistics","Manage course registrations","Support instructors and participants","Prepare training materials"]',
  '["تنسيق جداول التدريب واللوجستيات","إدارة تسجيلات الدورات","دعم المدربين والمشاركين","إعداد مواد التدريب"]',
  '["Bachelor''s degree","1+ years in training or administration","Strong organizational skills","Good communication"]',
  '["درجة البكالوريوس","خبرة سنة أو أكثر في التدريب أو الإدارة","مهارات تنظيم قوية","تواصل جيد"]',
  '["Experience with training programs is a plus"]',
  '["خبرة في برامج التدريب ميزة إضافية"]',
  '["Organization","Communication","Microsoft Office","Customer service"]',
  '["التنظيم","التواصل","Microsoft Office","خدمة العملاء"]',
  'Amman, Jordan', 'عمّان، الأردن', 'full_time', 'published', 3
),
(
  'f2000000-0000-0000-0000-000000000004',
  'data-analytics-instructor',
  'Data Analytics Instructor (Sample)', 'مدرب تحليل بيانات (نموذج)',
  'Training & Development', 'التدريب والتطوير',
  'Deliver data analytics and business intelligence training courses. Sample vacancy.',
  'تقديم دورات تدريبية في تحليل البيانات وذكاء الأعمال. وظيفة نموذجية.',
  '["Deliver data analytics courses","Prepare curriculum and exercises","Assess participant progress","Support participants during projects"]',
  '["تقديم دورات تحليل البيانات","إعداد المناهج والتمارين","تقييم تقدم المشاركين","دعم المشاركين أثناء المشاريع"]',
  '["Bachelor''s degree in a relevant field","Experience with BI and analytics tools","Strong teaching ability","Good communication"]',
  '["درجة البكالوريوس في مجال ذي صلة","خبرة في أدوات ذكاء الأعمال والتحليل","قدرة تعليمية قوية","تواصل جيد"]',
  '["Training or teaching experience is a plus"]',
  '["خبرة التدريب أو التعليم ميزة إضافية"]',
  '["Data analysis","Dashboard tools","Instruction","Communication"]',
  '["تحليل البيانات","أدوات لوحات المعلومات","التدريس","التواصل"]',
  'Amman, Jordan', 'عمّان، الأردن', 'contract', 'published', 4
),
(
  'f2000000-0000-0000-0000-000000000005',
  'administrative-coordinator',
  'Administrative Coordinator (Sample)', 'منسق إداري (نموذج)',
  'Administration', 'الإدارة',
  'Support day-to-day administrative operations across the organization. Sample vacancy.',
  'دعم العمليات الإدارية اليومية في المؤسسة. وظيفة نموذجية.',
  '["Handle administrative tasks","Manage documents and files","Support team coordination","Assist with scheduling and communication"]',
  '["التعامل مع المهام الإدارية","إدارة المستندات والملفات","دعم تنسيق الفريق","المساعدة في الجدولة والتواصل"]',
  '["Diploma or bachelor''s degree","1+ years administrative experience","Strong organizational skills","Good communication"]',
  '["دبلوم أو درجة البكالوريوس","خبرة سنة أو أكثر في العمل الإداري","مهارات تنظيم قوية","تواصل جيد"]',
  '["Experience in consulting is a plus"]',
  '["خبرة في الاستشارات ميزة إضافية"]',
  '["Organization","Communication","Microsoft Office","Time management"]',
  '["التنظيم","التواصل","Microsoft Office","إدارة الوقت"]',
  'Amman, Jordan', 'عمّان، الأردن', 'full_time', 'published', 5
);
