-- =============================================================================
-- 3DMCC — Seed: Services
-- =============================================================================

insert into public.services (
  id, slug, title_en, title_ar,
  short_description_en, short_description_ar,
  full_description_en, full_description_ar,
  benefits_en, benefits_ar,
  what_we_offer_en, what_we_offer_ar,
  who_for_en, who_for_ar,
  process_en, process_ar,
  icon, category_id, status, featured, sort_order
) values
(
  'f0000000-0000-0000-0000-000000000001',
  'rules-procedures-iso-coordination',
  'Rules, Procedures & ISO Coordination', 'الأنظمة والإجراءات والتنسيق مع الأيزو',
  'Develop and document clear policies, procedures and management systems aligned with ISO standards.',
  'تطوير وتوثيق سياسات وإجراءات وأنظمة إدارة واضحة متوافقة مع معايير الأيزو.',
  'We help organizations design, document and implement the rules, procedures and management systems they need to operate consistently and prepare for ISO certification. Our team coordinates the full lifecycle from gap analysis to documentation, internal audits and certification readiness.',
  'نساعد المؤسسات على تصميم وتوثيق وتطبيق الأنظمة والإجراءات وأنظمة الإدارة اللازمة للعمل بشكل متسق والاستعداد لشهادة الأيزو. ينسق فريقنا دورة الحياة الكاملة من تحليل الفجوات إلى التوثيق والتدقيق الداخلي والجاهزية للاعتماد.',
  '["Clear and compliant documentation","ISO certification readiness","Consistent internal processes"]',
  '["توثيق واضح ومتوافق","الجاهزية لشهادة الأيزو","عمليات داخلية متسقة"]',
  '["Policy and procedure writing","ISO gap analysis","Management system documentation","Internal audit support"]',
  '["كتابة السياسات والإجراءات","تحليل فجوات الأيزو","توثيق نظام الإدارة","دعم التدقيق الداخلي"]',
  '["Organizations pursuing ISO certification","Companies formalizing internal rules","Teams needing structured procedures"]',
  '["المؤسسات الساعية لشهادة الأيزو","الشركات التي تنظّم قواعدها الداخلية","الفرق التي تحتاج إجراءات منظمة"]',
  '["Assess current documentation","Design policies and procedures","Implement management system","Prepare for certification"]',
  '["تقييم الوثائق الحالية","تصميم السياسات والإجراءات","تطبيق نظام الإدارة","الاستعداد للاعتماد"]',
  'ClipboardCheck', 'b0000000-0000-0000-0000-000000000001', 'published', true, 1
),
(
  'f0000000-0000-0000-0000-000000000002',
  'human-resources-outsourcing',
  'Human Resources Outsourcing', 'التعهيد الخارجي للموارد البشرية',
  'Outsource your HR operations to a dedicated team and focus on your core business.',
  'قم بتعهيد عمليات الموارد البشرية لفريق متخصص وركّز على أعمالك الأساسية.',
  'Our HR outsourcing service lets organizations delegate day-to-day human resources operations — from employee files and contracts to compliance and payroll coordination — to experienced professionals, reducing overhead and improving efficiency.',
  'تتيح خدمة تعهيد الموارد البشرية للمؤسسات تفويض العمليات اليومية للموارد البشرية — من ملفات الموظفين والعقود إلى الامتثال وتنسيق الرواتب — لمحترفين ذوي خبرة، مما يقلل التكاليف ويحسن الكفاءة.',
  '["Reduced administrative overhead","HR compliance and accuracy","Focus on core business"]',
  '["تقليل الأعباء الإدارية","امتثال ودقة في الموارد البشرية","التركيز على الأعمال الأساسية"]',
  '["Employee records management","Contracts and onboarding","HR policy administration","Payroll coordination"]',
  '["إدارة سجلات الموظفين","العقود والالتحاق بالعمل","إدارة سياسات الموارد البشرية","تنسيق الرواتب"]',
  '["SMEs without a dedicated HR team","Growing companies scaling headcount","Organizations optimizing HR costs"]',
  '["الشركات الصغيرة والمتوسطة دون فريق HR متخصص","الشركات النامية التي تزيد عدد موظفيها","المؤسسات التي تحسّن تكاليف HR"]',
  '["Understand HR needs","Design outsourcing scope","Transition operations","Provide ongoing support"]',
  '["فهم احتياجات الموارد البشرية","تصميم نطاق التعهيد","نقل العمليات","تقديم دعم مستمر"]',
  'Users', 'b0000000-0000-0000-0000-000000000001', 'published', true, 2
),
(
  'f0000000-0000-0000-0000-000000000003',
  'payroll-services',
  'Payroll Services', 'خدمات الرواتب',
  'Accurate, timely and compliant payroll processing built around your organization.',
  'معالجة رواتب دقيقة وفي الوقت المحدد ومتوافقة مع الأنظمة، مصممة وفق مؤسستك.',
  'We manage the complete payroll cycle — calculations, deductions, allowances and statutory compliance — ensuring employees are paid accurately and on time while the organization remains compliant with local regulations.',
  'ندير دورة الرواتب الكاملة — الحسابات والاستقطاعات والعلاوات والامتثال القانوني — بما يضمن دفع رواتب الموظفين بدقة وفي الموعد، مع بقاء المؤسسة متوافقة مع الأنظمة المحلية.',
  '["Accurate and on-time payroll","Statutory compliance","Reduced payroll errors"]',
  '["رواتب دقيقة وفي الموعد","امتثال قانوني","تقليل أخطاء الرواتب"]',
  '["Salary and allowance calculation","Deductions and benefits","Payroll reports and slips","Compliance handling"]',
  '["حساب الرواتب والعلاوات","الاستقطاعات والمزايا","تقارير وقسائم الرواتب","معالجة الامتثال"]',
  '["Businesses of all sizes","Organizations with complex payroll","Companies seeking payroll accuracy"]',
  '["الشركات بجميع أحجامها","المؤسسات ذات الرواتب المعقدة","الشركات الساعية لدقة الرواتب"]',
  '["Collect payroll data","Calculate salaries","Validate and approve","Process and report"]',
  '["جمع بيانات الرواتب","حساب الرواتب","التحقق والاعتماد","المعالجة وإصدار التقارير"]',
  'Wallet', 'b0000000-0000-0000-0000-000000000001', 'published', true, 3
),
(
  'f0000000-0000-0000-0000-000000000004',
  'hr-performance-management',
  'HR & Performance Management', 'الموارد البشرية وإدارة الأداء',
  'Build a performance-driven culture with structured appraisal and development frameworks.',
  'ابنِ ثقافة قائمة على الأداء مع أطر تقييم وتطوير منظمة.',
  'We design and implement performance management systems that align individual goals with organizational strategy, covering KPIs, appraisal cycles, feedback and development planning to drive measurable improvement.',
  'نصمم وننفذ أنظمة إدارة الأداء التي تربط الأهداف الفردية باستراتيجية المؤسسة، وتشمل مؤشرات الأداء ودورات التقييم والتغذية الراجعة وتخطيط التطوير لتحقيق تحسين قابل للقياس.',
  '["Aligned individual and company goals","Objective performance evaluation","Continuous development"]',
  '["مواءمة الأهداف الفردية وأهداف الشركة","تقييم أداء موضوعي","تطوير مستمر"]',
  '["KPI design and cascading","Appraisal cycle management","Feedback and coaching frameworks","Development planning"]',
  '["تصميم وتوزيع مؤشرات الأداء","إدارة دورة التقييم","أطر التغذية الراجعة والتدريب","تخطيط التطوير"]',
  '["Organizations improving performance culture","HR teams building appraisal systems","Managers seeking structured reviews"]',
  '["المؤسسات التي تحسّن ثقافة الأداء","فرق HR التي تبني أنظمة التقييم","المديرون الساعون لتقييم منظم"]',
  '["Define performance framework","Set KPIs and goals","Run appraisal cycles","Review and develop"]',
  '["تحديد إطار الأداء","وضع المؤشرات والأهداف","تشغيل دورات التقييم","المراجعة والتطوير"]',
  'Target', 'b0000000-0000-0000-0000-000000000001', 'published', true, 4
),
(
  'f0000000-0000-0000-0000-000000000005',
  'time-attendance',
  'Time & Attendance', 'الوقت والحضور',
  'Track working time accurately with systems designed for accountability and compliance.',
  'تابع وقت العمل بدقة باستخدام أنظمة مصممة للمساءلة والامتثال.',
  'We implement time and attendance solutions that capture working hours, leaves and overtime accurately, giving organizations reliable data for payroll, compliance and workforce planning.',
  'ننفذ حلول الوقت والحضور التي تسجل ساعات العمل والإجازات والعمل الإضافي بدقة، مما يمنح المؤسسات بيانات موثوقة للرواتب والامتثال وتخطيط القوى العاملة.',
  '["Accurate time tracking","Simplified leave management","Payroll-ready data"]',
  '["تتبع دقيق للوقت","إدارة مبسطة للإجازات","بيانات جاهزة للرواتب"]',
  '["Attendance system setup","Leave and absence management","Overtime tracking","Attendance reporting"]',
  '["إعداد نظام الحضور","إدارة الإجازات والغياب","تتبع العمل الإضافي","تقارير الحضور"]',
  '["Organizations of all sizes","Companies managing shift work","HR teams tracking attendance"]',
  '["المؤسسات بجميع أحجامها","الشركات التي تدير نوبات العمل","فرق HR التي تتابع الحضور"]',
  '["Assess attendance needs","Configure time system","Integrate with payroll","Monitor and report"]',
  '["تقييم احتياجات الحضور","إعداد نظام الوقت","الربط مع الرواتب","المتابعة وإصدار التقارير"]',
  'Clock', 'b0000000-0000-0000-0000-000000000001', 'published', true, 5
),
(
  'f0000000-0000-0000-0000-000000000006',
  'employee-self-services',
  'Employee Self Services', 'الخدمة الذاتية للموظفين',
  'Empower employees with self-service portals for HR requests, documents and information.',
  'مكّن موظفيك من خلال بوابات الخدمة الذاتية لطلبات الموارد البشرية والمستندات والمعلومات.',
  'We help organizations deploy employee self-service portals where staff can view payslips, request leaves, update information and access HR documents — reducing HR workload and improving the employee experience.',
  'نساعد المؤسسات على نشر بوابات الخدمة الذاتية للموظفين، حيث يمكن للموظفين الاطلاع على قسائم الرواتب وطلب الإجازات وتحديث المعلومات والوصول إلى مستندات الموارد البشرية — مما يقلل عبء العمل ويحسّن تجربة الموظف.',
  '["Empowered employees","Reduced HR admin load","Faster request processing"]',
  '["موظفون متمكنون","تقليل الأعباء الإدارية على HR","معالجة أسرع للطلبات"]',
  '["Self-service portal setup","Leave and request workflows","Document access","Employee data updates"]',
  '["إعداد بوابة الخدمة الذاتية","سير عمل الإجازات والطلبات","الوصول إلى المستندات","تحديث بيانات الموظفين"]',
  '["Organizations digitizing HR","Companies improving employee experience","HR teams reducing manual work"]',
  '["المؤسسات التي ترقمن الموارد البشرية","الشركات التي تحسّن تجربة الموظف","فرق HR التي تقلل العمل اليدوي"]',
  '["Identify self-service needs","Configure portal","Train employees","Launch and support"]',
  '["تحديد احتياجات الخدمة الذاتية","إعداد البوابة","تدريب الموظفين","الإطلاق والدعم"]',
  'MonitorSmartphone', 'b0000000-0000-0000-0000-000000000001', 'published', true, 6
),
(
  'f0000000-0000-0000-0000-000000000007',
  'economic-feasibility-studies',
  'Economic Feasibility Studies', 'دراسات الجدوى الاقتصادية',
  'Data-driven feasibility studies that support confident investment and project decisions.',
  'دراسات جدوى قائمة على البيانات تدعم قرارات الاستثمار والمشاريع بثقة.',
  'We prepare comprehensive economic feasibility studies covering market analysis, financial projections, risk assessment and viability, helping investors and businesses make informed decisions before committing resources.',
  'نعدّ دراسات جدوى اقتصادية شاملة تغطي تحليل السوق والتوقعات المالية وتقييم المخاطر والجدوى، لمساعدة المستثمرين والشركات على اتخاذ قرارات مستنيرة قبل تخصيص الموارد.',
  '["Informed investment decisions","Clear financial projections","Risk identification"]',
  '["قرارات استثمار مستنيرة","توقعات مالية واضحة","تحديد المخاطر"]',
  '["Market and competitor analysis","Financial modeling","Risk assessment","Viability recommendations"]',
  '["تحليل السوق والمنافسين","النمذجة المالية","تقييم المخاطر","توصيات الجدوى"]',
  '["Entrepreneurs and startups","Investors evaluating opportunities","Organizations planning projects"]',
  '["رواد الأعمال والشركات الناشئة","المستثمرون الذين يقيّمون الفرص","المؤسسات التي تخطط للمشاريع"]',
  '["Define study scope","Collect and analyze data","Build financial model","Deliver feasibility report"]',
  '["تحديد نطاق الدراسة","جمع البيانات وتحليلها","بناء النموذج المالي","تسليم تقرير الجدوى"]',
  'LineChart', 'b0000000-0000-0000-0000-000000000001', 'published', true, 7
),
(
  'f0000000-0000-0000-0000-000000000008',
  'wealth-management-investment-consulting',
  'Wealth Management & Investment Consulting', 'إدارة الثروات والاستشارات الاستثمارية',
  'Strategic guidance to protect and grow wealth through informed investment decisions.',
  'إرشاد استراتيجي لحماية الثروة وتنميتها من خلال قرارات استثمارية مستنيرة.',
  'We provide advisory services that help individuals and organizations structure their wealth and evaluate investment opportunities, balancing risk and return according to their goals and circumstances.',
  'نقدم خدمات استشارية تساعد الأفراد والمؤسسات على هيكلة ثرواتهم وتقييم الفرص الاستثمارية، بما يوازن بين المخاطر والعائد وفق أهدافهم وظروفهم.',
  '["Goal-aligned investment strategy","Risk and return balance","Ongoing advisory support"]',
  '["استراتيجية استثمار متوافقة مع الأهداف","توازن المخاطر والعائد","دعم استشاري مستمر"]',
  '["Portfolio and investment review","Wealth structuring guidance","Opportunity evaluation","Financial advisory"]',
  '["مراجعة المحفظة والاستثمار","إرشاد هيكلة الثروة","تقييم الفرص","استشارات مالية"]',
  '["Individuals managing wealth","Investors seeking guidance","Family and business owners"]',
  '["الأفراد الذين يديرون ثرواتهم","المستثمرون الباحثون عن إرشاد","أصحاب الأعمال والعائلات"]',
  '["Understand financial goals","Assess current position","Design strategy","Monitor and advise"]',
  '["فهم الأهداف المالية","تقييم الوضع الحالي","تصميم الاستراتيجية","المتابعة والإرشاد"]',
  'PiggyBank', 'b0000000-0000-0000-0000-000000000001', 'published', true, 8
),
(
  'f0000000-0000-0000-0000-000000000009',
  'hr-consulting-advisory',
  'HR Consulting & Advisory', 'الاستشارات والإرشاد في الموارد البشرية',
  'Expert HR guidance to build effective people practices and a strong organization.',
  'إرشاد خبير في الموارد البشرية لبناء ممارسات فعالة ومنظمة قوية.',
  'Our HR advisory service helps leaders make better people decisions across hiring, compensation, employee relations, policies and organizational design, providing practical recommendations tailored to each business.',
  'تساعد خدمة الاستشارات في الموارد البشرية القادة على اتخاذ قرارات أفضل بشأن التوظيف والتعويضات وعلاقات الموظفين والسياسات والتصميم التنظيمي، مع توصيات عملية مصممة لكل عمل.',
  '["Practical HR recommendations","Stronger people practices","Aligned HR strategy"]',
  '["توصيات عملية في الموارد البشرية","ممارسات أقوى للأفراد","استراتيجية HR متوافقة"]',
  '["HR strategy and planning","Compensation and benefits","Employee relations","Organizational design"]',
  '["استراتيجية وتخطيط الموارد البشرية","التعويضات والمزايا","علاقات الموظفين","التصميم التنظيمي"]',
  '["Business owners and leaders","HR managers seeking expertise","Growing organizations"]',
  '["أصحاب الأعمال والقادة","مديرو HR الباحثون عن خبرة","المؤسسات النامية"]',
  '["Diagnose HR needs","Recommend solutions","Support implementation","Evaluate impact"]',
  '["تشخيص احتياجات HR","التوصية بالحلول","دعم التنفيذ","تقييم الأثر"]',
  'Handshake', 'b0000000-0000-0000-0000-000000000001', 'published', true, 9
),
(
  'f0000000-0000-0000-0000-000000000010',
  'corporate-finance-accounting-consulting',
  'Corporate Finance & Accounting Consulting', 'استشارات التمويل والمحاسبة للشركات',
  'Strengthen financial management, reporting and planning for sustainable performance.',
  'عزّز الإدارة المالية والتقارير والتخطيط لتحقيق أداء مستدام.',
  'We advise organizations on financial management, accounting practices, budgeting and reporting, helping them improve financial control, make better decisions and meet compliance requirements.',
  'نقدم المشورة للمؤسسات حول الإدارة المالية والممارسات المحاسبية والميزانيات والتقارير، لمساعدتها على تحسين الرقابة المالية واتخاذ قرارات أفضل والوفاء بمتطلبات الامتثال.',
  '["Improved financial control","Better financial decisions","Compliance readiness"]',
  '["تحسين الرقابة المالية","قرارات مالية أفضل","الجاهزية للامتثال"]',
  '["Financial planning and budgeting","Accounting process review","Financial reporting","Cash flow management"]',
  '["التخطيط المالي والميزانيات","مراجعة العمليات المحاسبية","التقارير المالية","إدارة التدفق النقدي"]',
  '["SMEs and corporations","Finance teams seeking improvement","Organizations planning growth"]',
  '["الشركات الصغيرة والمتوسطة والكبيرة","فرق المالية الساعية للتحسين","المؤسسات التي تخطط للنمو"]',
  '["Assess financial health","Design improvements","Implement practices","Monitor performance"]',
  '["تقييم الصحة المالية","تصميم التحسينات","تطبيق الممارسات","متابعة الأداء"]',
  'Calculator', 'b0000000-0000-0000-0000-000000000001', 'published', true, 10
),
(
  'f0000000-0000-0000-0000-000000000011',
  'architecture-design-consultation',
  'Architecture Design Consultation', 'الاستشارات في التصميم المعماري',
  'Design consultation that translates vision into functional, inspiring spaces.',
  'استشارات تصميم تحوّل الرؤية إلى مساحات عملية وملهمة.',
  'We provide architecture design consultation services that guide clients from concept to detailed design, balancing aesthetics, functionality and practicality to create spaces that serve their purpose and inspire.',
  'نقدم خدمات استشارية في التصميم المعماري ترشد العملاء من الفكرة إلى التصميم التفصيلي، بما يوازن بين الجماليات والوظيفة والعملية لإنشاء مساحات تخدم غرضها وتلهم.',
  '["Vision-led design","Functional and aesthetic spaces","Practical project guidance"]',
  '["تصميم مبني على الرؤية","مساحات عملية وجمالية","إرشاد عملي للمشاريع"]',
  '["Concept design","Space planning","Design consultation","Project planning support"]',
  '["التصميم المبدئي","تخطيط المساحات","الاستشارات التصميمية","دعم تخطيط المشاريع"]',
  '["Businesses designing spaces","Individuals planning projects","Developers seeking design guidance"]',
  '["الشركات التي تصمم مساحات","الأفراد الذين يخططون لمشاريع","المطورون الباحثون عن إرشاد تصميمي"]',
  '["Understand vision and needs","Develop concepts","Refine design","Support implementation"]',
  '["فهم الرؤية والاحتياجات","تطوير المفاهيم","تحسين التصميم","دعم التنفيذ"]',
  'Building2', 'b0000000-0000-0000-0000-000000000002', 'published', true, 11
),
(
  'f0000000-0000-0000-0000-000000000012',
  'design-advisory',
  'Design Advisory', 'الإرشاد في التصميم',
  'Strategic design guidance to help you make the right decisions for your space or project.',
  'إرشاد تصميمي استراتيجي لمساعدتك على اتخاذ القرارات الصحيحة لمساحتك أو مشروعك.',
  'Our design advisory service supports clients through the design decision-making process, offering independent guidance on layout, materials, styling and project direction to achieve the best outcome.',
  'تدعم خدمة الإرشاد في التصميم العملاء خلال عملية اتخاذ القرارات التصميمية، وتقدم إرشاداً مستقلاً حول التخطيط والمواد والأسلوب واتجاه المشروع لتحقيق أفضل نتيجة.',
  '["Informed design decisions","Independent expert guidance","Optimized project outcomes"]',
  '["قرارات تصميم مستنيرة","إرشاد خبير مستقل","نتائج مشروع محسّنة"]',
  '["Design review and feedback","Layout and materials advice","Style direction","Project direction support"]',
  '["مراجعة التصميم والتغذية الراجعة","إرشاد التخطيط والمواد","توجيه الأسلوب","دعم اتجاه المشروع"]',
  '["Clients planning design work","Teams needing design direction","Project owners reviewing proposals"]',
  '["العملاء الذين يخططون لأعمال التصميم","الفرق التي تحتاج توجيهاً تصميمياً","أصحاب المشاريع الذين يراجعون العروض"]',
  '["Review current state","Advise on direction","Refine choices","Support decisions"]',
  '["مراجعة الوضع الحالي","تقديم المشورة حول الاتجاه","تحسين الاختيارات","دعم القرارات"]',
  'PencilRuler', 'b0000000-0000-0000-0000-000000000002', 'published', false, 12
),
(
  'f0000000-0000-0000-0000-000000000013',
  'project-planning-support',
  'Project Planning Support', 'دعم تخطيط المشاريع',
  'Structure your project for success with clear planning and coordination support.',
  'نظّم مشروعك للنجاح من خلال دعم واضح في التخطيط والتنسيق.',
  'We support clients in planning and structuring their projects, from scope definition and sequencing to coordination and milestone tracking, ensuring smoother execution and fewer surprises.',
  'ندعم العملاء في تخطيط وهيكلة مشاريعهم، من تحديد النطاق والتسلسل إلى التنسيق وتتبع المراحل، بما يضمن تنفيذاً أكثر سلاسة ومفاجآت أقل.',
  '["Clear project structure","Smoother execution","Reduced project risk"]',
  '["هيكلة واضحة للمشروع","تنفيذ أكثر سلاسة","تقليل مخاطر المشروع"]',
  '["Scope and milestone planning","Project coordination","Schedule support","Progress tracking"]',
  '["تخطيط النطاق والمراحل","تنسيق المشروع","دعم الجدول الزمني","تتبع التقدم"]',
  '["Project owners and developers","Teams starting new projects","Organizations coordinating work"]',
  '["أصحاب المشاريع والمطورون","الفرق التي تبدأ مشاريع جديدة","المؤسسات التي تنسق العمل"]',
  '["Define scope","Plan milestones","Coordinate stakeholders","Track progress"]',
  '["تحديد النطاق","تخطيط المراحل","تنسيق الأطراف","تتبع التقدم"]',
  'CalendarCheck', 'b0000000-0000-0000-0000-000000000002', 'published', false, 13
),
(
  'f0000000-0000-0000-0000-000000000014',
  'design-coordination',
  'Design Coordination', 'تنسيق التصميم',
  'Coordinate design efforts across disciplines for a cohesive, on-track project.',
  'نسّق جهود التصميم عبر التخصصات لتحقيق مشروع متماسك وفي المسار الصحيح.',
  'We coordinate design activities across teams and disciplines, aligning architectural, technical and functional requirements so the final result is cohesive, consistent and delivered on track.',
  'ننسق أنشطة التصميم عبر الفرق والتخصصات، بما يوفّق بين المتطلبات المعمارية والتقنية والوظيفية لتكون النتيجة النهائية متماسكة ومتسقة وتُسلَّم في المسار الصحيح.',
  '["Cohesive design outcomes","Aligned project teams","On-track delivery"]',
  '["نتائج تصميم متماسكة","فرق مشروع متوافقة","تسليم في المسار الصحيح"]',
  '["Cross-discipline coordination","Requirements alignment","Design consistency review","Delivery support"]',
  '["تنسيق عبر التخصصات","مواءمة المتطلبات","مراجعة اتساق التصميم","دعم التسليم"]',
  '["Multi-team projects","Developers and architects","Organizations with complex projects"]',
  '["المشاريع متعددة الفرق","المطورون والمعماريون","المؤسسات ذات المشاريع المعقدة"]',
  '["Map design scope","Coordinate disciplines","Review consistency","Support delivery"]',
  '["رسم نطاق التصميم","تنسيق التخصصات","مراجعة الاتساق","دعم التسليم"]',
  'Network', 'b0000000-0000-0000-0000-000000000002', 'published', false, 14
);
