import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  BookMarked,
  BookOpen,
  Building2,
  CalendarCheck,
  Calculator,
  ClipboardCheck,
  Clock,
  Compass,
  FileText,
  Gauge,
  GraduationCap,
  Handshake,
  HeartHandshake,
  Layers,
  LineChart,
  Mail,
  MapPin,
  MonitorSmartphone,
  Network,
  PencilRuler,
  Phone,
  PiggyBank,
  Puzzle,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Wallet,
  Workflow,
  type LucideProps,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  BarChart3,
  BookMarked,
  BookOpen,
  Building2,
  CalendarCheck,
  Calculator,
  ClipboardCheck,
  Clock,
  Compass,
  FileText,
  Gauge,
  GraduationCap,
  Handshake,
  HeartHandshake,
  Layers,
  LineChart,
  Mail,
  MapPin,
  MonitorSmartphone,
  Network,
  PencilRuler,
  Phone,
  PiggyBank,
  Puzzle,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Wallet,
  Workflow,
};

export function DynamicIcon({
  name,
  ...props
}: { name?: string | null } & Omit<LucideProps, "name">) {
  const Icon = (name && ICONS[name]) || Sparkles;
  return <Icon {...props} />;
}
